In [ ]:
import os
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# This allows the notebook to find the 'pysafer' folder in the parent directory
# sys.path.append(os.path.abspath('..'))

import pySAFER
print(f"包所在位置: {pySAFER.__file__}")
print(f"helpers.py 是否存在: {os.path.exists(os.path.join(os.path.dirname(pySAFER.__file__), 'helpers.py'))}")
from pySAFER.helpers import calc_ndvi

包所在位置: C:\GitHub\pySAFER\src\pySAFER\__init__.py
helpers.py 是否存在: True

In [ ]:
file_point_sample = r"C:\GitHub\pySAFER\Examples\point_samples.txt"
df = pd.read_csv(file_point_sample, sep='\t', parse_dates=['date'])
display(df.head(3))

        date        lat  Tmax  Tmin   red   nir
0 2025-05-01  37.365888  38.0  21.2  0.03  0.36
1 2025-05-02  37.365888  38.1  21.3  0.03  0.36
2 2025-05-03  37.365888  38.2  21.4  0.03  0.36

In [4]:
df['ndvi'] = pySAFER.calc_ndvi(df['red'], df['nir'])
display(df.head(3))

        date        lat  Tmax  Tmin   red   nir  calculated_ndvi      ndvi
0 2025-05-01  37.365888  38.0  21.2  0.03  0.36         0.846154  0.846154
1 2025-05-02  37.365888  38.1  21.3  0.03  0.36         0.846154  0.846154
2 2025-05-03  37.365888  38.2  21.4  0.03  0.36         0.846154  0.846154